image: docker:stable

stages:
  - test
  - release

variables:
  STAGING_REGISTRY: "registry.gitlab.com"

test:
  image: python:3.9
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover test
  only:
    changes:
      - bogi/**/*
      - test/**/*
      - requirements.txt

release:
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  script:
    - IMAGE_NAME=${STAGING_REGISTRY}/bigdataboutique/${CI_PROJECT_NAME}:`date '+%Y-%m-%d-%H%M'`-${CI_COMMIT_SHA:0:9}
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    changes:
      - bogi/**/*
      - test/**/*
      - requirements.txt
    refs:
      - master
