//@no-redirect
//@no-cookie-jar
GET http://google.com

>STATUS 301

### Comment next to the request will be treated as a request ID
### with-trailing-slash
GET https://google.com/

### without-trailing-slash
GET https://google.com

<> with-trailing-slash

###
GET https://github.com/BigDataBoutique.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 410, "Response status is not 410");
    });

    client.test("Headers option exists", function() {
        client.assert(response.body.hasOwnProperty("headers"), "Cannot find 'headers' option in response");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}
